
package gui;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import static java.lang.System.exit;
import java.time.LocalDateTime;
import javax.swing.*;
import pq1.Lista;
import pq1.Nodo;
import pq1.Propietario;
import pq1.Vehiculo;

/**
 *
 * @author rmmedina
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setTitle("Parqueadero");
    }

    String vehiculo;
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vehiculos = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        seleccionarCap = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        capacidad = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cjListado = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cjPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Propietario1 = new javax.swing.JLabel();
        carrosIngresados = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        motoIngresadas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        espacioDispo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblCapacidad = new javax.swing.JLabel();
        Moto = new javax.swing.JRadioButton();
        Carro = new javax.swing.JRadioButton();
        btIngresar = new javax.swing.JButton();
        cjPropietario = new javax.swing.JTextField();
        cjIdentificacion = new javax.swing.JTextField();
        BuscarVehiculo = new javax.swing.JButton();
        Pago = new javax.swing.JButton();
        Volver1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Construído por Roibert Medina - Rmmedina 2023");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setEnabled(false);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));
        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 90));

        seleccionarCap.setBackground(new java.awt.Color(255, 153, 51));
        seleccionarCap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        seleccionarCap.setForeground(new java.awt.Color(255, 255, 255));
        seleccionarCap.setText("Seleccionar Capacidad");
        seleccionarCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarCapActionPerformed(evt);
            }
        });
        jPanel5.add(seleccionarCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 220, 60));

        registrar.setBackground(new java.awt.Color(255, 153, 51));
        registrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setText("Registrar Ingreso");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        jPanel5.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 220, 60));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 470));

        jTabbedPane1.addTab("Menu Principal", jPanel4);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 153, 51));
        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 100));

        jLabel5.setText("Capacidad del Parqueadero: ");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 180, 20));

        capacidad.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        capacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacidadActionPerformed(evt);
            }
        });
        jPanel7.add(capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 160, 30));

        Guardar.setBackground(new java.awt.Color(255, 153, 51));
        Guardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel7.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 200, 50));

        Volver.setBackground(new java.awt.Color(255, 153, 51));
        Volver.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Volver.setForeground(new java.awt.Color(255, 255, 255));
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel7.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 200, 50));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 470));

        jTabbedPane1.addTab("Seleccionar Capacidad", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 170, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Uso Parqueadero");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(200, 10, 120, 16);

        cjListado.setEditable(false);
        cjListado.setColumns(20);
        cjListado.setRows(5);
        jScrollPane1.setViewportView(cjListado);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 490, 200);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 520, 250));

        jPanel11.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 960, 40));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Placa:");
        jPanel10.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        jPanel10.add(cjPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 150, -1));

        jLabel4.setText("Identificacion:");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 20));

        Propietario1.setText("Propietario:");
        jPanel10.add(Propietario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 20));

        carrosIngresados.setEditable(false);
        carrosIngresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrosIngresadosActionPerformed(evt);
            }
        });
        jPanel10.add(carrosIngresados, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 70, 20));

        jLabel2.setText("Carros ingresados:");
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 110, 20));

        motoIngresadas.setEditable(false);
        motoIngresadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motoIngresadasActionPerformed(evt);
            }
        });
        jPanel10.add(motoIngresadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 70, 20));

        jLabel8.setText("Motos ingresadas:");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 20));

        espacioDispo.setEditable(false);
        espacioDispo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espacioDispoActionPerformed(evt);
            }
        });
        jPanel10.add(espacioDispo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 70, 20));

        jLabel9.setText("Espacios disponibles:");
        jPanel10.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 130, 20));

        lblCapacidad.setText("Capacidad Max:   Vehiculos");
        jPanel10.add(lblCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 190, -1));

        Vehiculos.add(Moto);
        Moto.setText("Moto");
        Moto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotoActionPerformed(evt);
            }
        });
        jPanel10.add(Moto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 98, -1));

        Vehiculos.add(Carro);
        Carro.setText("Carro");
        Carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarroActionPerformed(evt);
            }
        });
        jPanel10.add(Carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 80, -1));

        btIngresar.setBackground(new java.awt.Color(255, 153, 0));
        btIngresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btIngresar.setText("Ingresar");
        btIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIngresarActionPerformed(evt);
            }
        });
        jPanel10.add(btIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 120, 30));
        jPanel10.add(cjPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, -1));
        jPanel10.add(cjIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 150, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 290, 380));

        BuscarVehiculo.setBackground(new java.awt.Color(255, 153, 51));
        BuscarVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BuscarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        BuscarVehiculo.setText("Buscar Vehiculo");
        BuscarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 180, 40));

        Pago.setBackground(new java.awt.Color(255, 153, 51));
        Pago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Pago.setForeground(new java.awt.Color(255, 255, 255));
        Pago.setText("Generar Pago");
        Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagoActionPerformed(evt);
            }
        });
        jPanel1.add(Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 160, 40));

        Volver1.setBackground(new java.awt.Color(255, 153, 51));
        Volver1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Volver1.setForeground(new java.awt.Color(255, 255, 255));
        Volver1.setText("Volver");
        Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver1ActionPerformed(evt);
            }
        });
        jPanel1.add(Volver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 160, 40));

        jTabbedPane1.addTab("Registro", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 930, 520);

        setSize(new java.awt.Dimension(943, 510));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIngresarActionPerformed
        // TODO add your handling code here:
        ingresar();
    }//GEN-LAST:event_btIngresarActionPerformed

    private void MotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotoActionPerformed
        // TODO add your handling code here:
        vehiculo = "Moto";
    }//GEN-LAST:event_MotoActionPerformed

    private void CarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarroActionPerformed
        // TODO add your handling code here:
        vehiculo = "Carro";
    }//GEN-LAST:event_CarroActionPerformed

    
    private void carrosIngresadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrosIngresadosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_carrosIngresadosActionPerformed

    private void espacioDispoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espacioDispoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_espacioDispoActionPerformed

    private void motoIngresadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motoIngresadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motoIngresadasActionPerformed

    private void seleccionarCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarCapActionPerformed
       
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_seleccionarCapActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_registrarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
           try {
        int nuevaCapacidad = Integer.parseInt(capacidad.getText());
        lista.tamañoParqueadero = nuevaCapacidad;
        lista.contCantidad = nuevaCapacidad - (lista.contCarro + lista.contMoto); // ajustar la cantidad disponible

        lblCapacidad.setText("Capacidad Max " + nuevaCapacidad + " Vehículos");
        espacioDispo.setText(String.valueOf(lista.contCantidad));

        JOptionPane.showMessageDialog(this, "Capacidad actualizada correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
        jTabbedPane1.setSelectedIndex(0);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_GuardarActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_VolverActionPerformed

    private void BuscarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarVehiculoActionPerformed

    private void PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagoActionPerformed
       generarPago();
    }//GEN-LAST:event_PagoActionPerformed

    private void Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver1ActionPerformed
     jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_Volver1ActionPerformed

    private void capacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    Lista lista = new Lista();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarVehiculo;
    private javax.swing.JRadioButton Carro;
    private javax.swing.JButton Guardar;
    private javax.swing.JRadioButton Moto;
    private javax.swing.JButton Pago;
    private javax.swing.JLabel Propietario1;
    private javax.swing.ButtonGroup Vehiculos;
    private javax.swing.JButton Volver;
    private javax.swing.JButton Volver1;
    private javax.swing.JButton btIngresar;
    private javax.swing.JTextField capacidad;
    private javax.swing.JTextField carrosIngresados;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextArea cjListado;
    private javax.swing.JTextField cjPlaca;
    private javax.swing.JTextField cjPropietario;
    private javax.swing.JTextField espacioDispo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JTextField motoIngresadas;
    private javax.swing.JButton registrar;
    private javax.swing.JButton seleccionarCap;
    // End of variables declaration//GEN-END:variables

    private void ingresar() {
        
        if (lista.tamañoParqueadero <= 0) {
        JOptionPane.showMessageDialog(this, "Seleccione la capacidad del parqueadero primero.", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
        return;
    }
        Vehiculo vehiculo = new Vehiculo();
        Nodo nodo = new Nodo(vehiculo);
        
        vehiculo.placa = cjPlaca.getText();
        vehiculo.propietario.modificarIdentificaion(cjIdentificacion.getText());
        vehiculo.propietario.modificarNombre(cjPropietario.getText());
        vehiculo.vehiculo= this.vehiculo;
        vehiculo.fechaIngreso= LocalDateTime.now();
        vehiculo.strFechaIngreso= vehiculo.obtenerFecha();
        
        if (lista.contCantidad >0){
            
            if(this.vehiculo == "Moto" && lista.contMoto >= lista.tamañoParqueadero*0.4 ){
                JOptionPane.showMessageDialog(this, "El cupo de motos esta completo", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        
            if(this.vehiculo == "Carro" && lista.contCarro >= lista.tamañoParqueadero*0.6 ){
                JOptionPane.showMessageDialog(this, "El cupo de carros esta completo", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            lista.adicionarNodoFin(nodo);
            lista.contCantidad-=1;
            if (this.vehiculo == "Moto") {
                lista.contMoto ++;
            }else if ( this.vehiculo == "Carro" ){
                lista.contCarro ++;
            }
            
             persistir(vehiculo);
            JOptionPane.showMessageDialog(this, "Ingresa vehìculo", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
            this.actualizaListado();
        }
            limpiarCampos();
        if (lista.contCantidad <= 0){
            JOptionPane.showMessageDialog(this, "El cupo del parqueadero esta completo", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
        }
         
        
        this.carrosIngresados.setText(Integer.toString(lista.contCarro));
        this.motoIngresadas.setText(Integer.toString(lista.contMoto));
        this.espacioDispo.setText(Integer.toString(lista.contCantidad));

    }

    private void atender() {
        JOptionPane.showMessageDialog(this, "Factura Generada", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
        Vehiculo vehiculo = new Vehiculo();
        Nodo nodo = new Nodo(vehiculo);
        vehiculo.strFechaSalida= vehiculo.obtenerFecha();
        lista.contCantidad+=1;
        String tipoV= lista.nodoPrincipal.informacion.vehiculo;
              if (tipoV == "Moto") {
                lista.contMoto -=1;
        }else if (tipoV == "Carro" ){
            lista.contCarro -=1;
        }

       // this.cjListado1.setText(lista.infoNodo()+"\nHora de ingreso: "+lista.nodoPrincipal.informacion.strFechaIngreso+"\nHora de salida: "+vehiculo.strFechaSalida+"\nValor a pagar: "+vehiculo.calcularPago(lista.nodoPrincipal.informacion.vehiculo,lista.nodoPrincipal.informacion.fechaIngreso));
        
        lista.borrarPrimero(nodo);
        this.actualizaListado();
        
        this.carrosIngresados.setText(Integer.toString(lista.contCarro));
        this.motoIngresadas.setText(Integer.toString(lista.contMoto));
        this.espacioDispo.setText(Integer.toString(lista.contCantidad));
    }
    
    private void actualizaListado(){
        String sb = lista.obtenerLista();
        this.cjListado.setText(sb);
    }
    
    private void persistir(Vehiculo vehiculo) {
    try {
        FileOutputStream fileOut = new FileOutputStream("vehiculo.dat");
        ObjectOutputStream out = new ObjectOutputStream(fileOut);
        out.writeObject(vehiculo);
        out.close();
        fileOut.close();
        System.out.println("Datos del vehículo han sido Persistidos: " + vehiculo);
    } catch (IOException i) {
        i.printStackTrace();
    }
  }
    private void limpiarCampos() {
    cjPlaca.setText("");
    cjIdentificacion.setText("");
    cjPropietario.setText("");
  }
    
private void generarPago() {
    // Pedir la placa del vehículo al usuario
    String placa = JOptionPane.showInputDialog(this, "Ingrese la placa del vehículo:", "Generar Pago", JOptionPane.PLAIN_MESSAGE);

    if (placa == null || placa.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "La placa no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    Nodo nodo = lista.buscarNodoPorPlaca(placa); // Busca el vehículo en la lista por su placa

    if (nodo != null) {
        Vehiculo vehiculo = nodo.informacion;
        double total = vehiculo.calcularPago(vehiculo.vehiculo, vehiculo.fechaIngreso);

        // Muestra los detalles del vehículo y el monto total a pagar
        JOptionPane.showMessageDialog(this,
            "Propietario: " + vehiculo.propietario.nombre + "\n" +
            "Identificación: " + vehiculo.propietario.identificaion + "\n" +
            "Placa: " + vehiculo.placa + "\n" +
            "Hora de ingreso: " + vehiculo.strFechaIngreso + "\n" +
            "Total a pagar: " + total + " pesos",
            "Detalles de Pago",
            JOptionPane.INFORMATION_MESSAGE);

        // Eliminar el vehículo de la lista
        lista.borrarNodoPorPlaca(placa);

        // Actualizar los contadores y espacios disponibles
        lista.contCantidad += 1; // Incrementar espacio disponible

        if ("Moto".equals(vehiculo.vehiculo)) {
            lista.contMoto -= 1; // Disminuir el contador de motos
        } else if ("Carro".equals(vehiculo.vehiculo)) {
            lista.contCarro -= 1; // Disminuir el contador de carros
        }

        // Actualizar la interfaz gráfica
        this.carrosIngresados.setText(Integer.toString(lista.contCarro));
        this.motoIngresadas.setText(Integer.toString(lista.contMoto));
        this.espacioDispo.setText(Integer.toString(lista.contCantidad));

        // Actualizar el JTextArea
        this.actualizaListado(); // Llama al método que actualiza el JTextArea

    } else {
        JOptionPane.showMessageDialog(this, "Vehículo no encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}


    private void salir() {
        System.exit(0);
    }
}

//AAAA
